name: polymer_element
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/dam0vm3nt
description: Polymer-2 support for Dart

version: 0.4.0
dependencies:
  js: any
  html5: ^0.0.4
